# used to define different services(i.e. containers)
# It is used for local development purposes.

services:
  node_app:
    container_name: node_app
    build: .
    image: sweekarbangera/node_live_app
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - node_db
    restart: always

  node_db:    # service name
    container_name: node_db   # container name is can be different than above service name
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:    # to keep the data persistance with containers
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
